<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>BarelyReal.App</RootNamespace>
    <AssemblyName>BarelyReal.App</AssemblyName>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <ApplicationIcon>Assets\BarelyReal.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Core\BarelyReal.Core.csproj" />
    <Resource Include="Assets\BarelyReal.ico" />
    <Resource Include="Assets\BarelyReal.png" />
  </ItemGroup>

</Project>
